### ISSUE TITLE
Implement grid in list view

### ISSUE THREAD

**Issue by buremba** [jinjat-data/jinjat#12]
Enable a list view when the exposure has the following layout set:

```
exposures:
  - name: crud
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: AutoAwesome
          actions:
            delete: _delete_customers
          layout:
            list: grid
```

https://material-kit-react.devias.io/companies
