### ISSUE TITLE
Support dashboards

### ISSUE THREAD

**Issue by buremba** [jinjat-data/jinjat#14]
We should use React Grid Layout in read-only model to render the charts.

Here is an example exposure to be parsed:

```
- name: example_dashboard
    type: dashboard
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: AutoAwesome
        parameters:
          country:
            type: string
        items:
          - width: 1
            height: 1
            left: 2
            top: 2
            chart:
              dataset:
                analysis: example_endpoint
                body:
                  country: ${country}
                query_params:
              xAxis:
                type: category
              series:
                - type: bar
```
