### ISSUE TITLE
Markdown integration

### ISSUE THREAD

**Issue by buremba** [jinjat-data/jinjat#17]
Parse `notebook` type exposures and render `meta.jinjat.notebook` path from static files. https://mdxjs.com/

```
-   name: example_notebook
    type: notebook
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: AutoAwesome
        notebook_path: markdown/example_notebook.mdx
```
